CREATE TABLE IF NOT EXISTS account (
	account_id: integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_at: timestamp DEFAULT current_timestamp,
	modified_at: timestamp DEFAULT current_timestamp,
	user_name: varchar,
	email: varchar(254),
	full_name: varchar,
	password: varchar,
);

